apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: lab-service
spec:
  selector:
    app: lab-service
  ports:
    - protocol: TCP
      port: 80               
      targetPort: 8086       
      nodePort: 30005       
  type: NodePort              