 pipeline {
    agent any

    tools {
        maven 'Maven-4.0.0'
        jdk 'JDK17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hibayagoubi1/Labs-management.git'
            }
        }
        
   stage('Build and Test') {
      steps {
               bat 'cd LabsManagement-Registry && mvn clean package'
      }
    }
         stage('Static Code Analysis') {
  steps {
    withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_TOKEN')]) {
      bat "cd LabsManagement-Registry && mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=${SONAR_TOKEN}"
    }
  }
}    
       stage('Build and Push Docker Image') {
    steps {
        script {
            def dockerImageName = "hibayaagoubi/registry-service:${BUILD_NUMBER}"
            bat "cd LabsManagement-Registry && docker build -t ${dockerImageName} ."
            docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                docker.image(dockerImageName).push()
            }
        }
    }
}
  }
}
