pipeline {
    agent any

    tools {
        maven 'Maven-4.0.0'
        jdk 'JDK17'
    }

    environment {
        GIT_REPO_NAME = "Labs-management"
        GIT_USER_NAME = "hibayagoubi1"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/hibayagoubi1/Labs-management.git'
            }
        }

        stage('Build and Test') {
            steps {
                bat 'cd LabsManagement-gateway && mvn clean package'
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonarqube', variable: 'SONAR_TOKEN')]) {
                    bat "cd LabsManagement-gateway && mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=%SONAR_TOKEN%"
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    def dockerImageName = "hibayaagoubi/gateway-service:${BUILD_NUMBER}"
                    bat "cd LabsManagement-gateway && docker build -t ${dockerImageName} ."
                    docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
                        docker.image(dockerImageName).push()
                    }
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                    bat '''
                        git config user.email "your-email@example.com"
                        git config user.name "hibayagoubi1"
                        
                        # Remplacer dynamiquement le tag d'image dans le fichier YAML
                        powershell -Command "(gc spring-boot-app-manifests/deployment-gateway.yml) -replace 'replaceImageTag', '%BUILD_NUMBER%' | sc spring-boot-app-manifests/deployment-gateway.yml"
                        
                        # Ajouter et pousser les modifications
                        git add spring-boot-app-manifests/deployment-gateway.yml
                        git commit -m "Update deployment image to version %BUILD_NUMBER%"
                        git push https://%GITHUB_TOKEN%@github.com/%GIT_USER_NAME%/%GIT_REPO_NAME% HEAD:main
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs for details.'
        }
    }
}
