apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 80               
      targetPort: 8080        
      nodePort: 30001         
  type: NodePort              