apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 8083  # Le port sur lequel le service est exposé
      targetPort: 8080  # Le port sur lequel le conteneur écoute
  type: ClusterIP  # Le service est accessible à l'intérieur du cluster