spring:
  cloud:
    gateway:
      routes:
        - id: GestionUtilisateurs
          uri: http://gestionutilisateurs-service
          predicates:
            - Path=/utilisateurs/**
          filters:
            - AuthenticationFilter
            
        - id: identity-service
          uri: http://identity-service
          predicates:
            - Path=/auth/**
          metadata:
            cors:
              allowedOrigins: '*'
              allowedMethods:
                - GET
                - POST
              allowedHeaders: '*'

application:
  name: labsmanagement-gateway
